/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.Connection;

/**
 *
 * @author ACER
 */
public class MainView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());
    private final Connection connection;
    private PatientRecordsView patientRecordsView;
    private PatientVisitView patientVisitView;
    private RecordsView recordsView;
    /**
     * Creates new form MainView
     */
    public MainView(Connection connection) {
        this.connection = connection;
        initComponents();
        this.setSize(600, 500); // 🔧 set preferred startup size (width, height)
        this.setLocationRelativeTo(null); // 🎯 center the window on screen

        patientRecordsView = new PatientRecordsView(connection);
        patientVisitView = new PatientVisitView();
        recordsView = new RecordsView(connection);
        
        MainPanel.add(patientRecordsView, "patientRecordsCard");
        MainPanel.add(patientVisitView, "patientVisitCard");
        MainPanel.add(recordsView, "recordsCard");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        lblHeader = new javax.swing.JLabel();
        panelSide = new javax.swing.JPanel();
        btnPatientRecords = new javax.swing.JButton();
        btnDoctorRecords = new javax.swing.JButton();
        btnDiseaseRecords = new javax.swing.JButton();
        btnLabProcedures = new javax.swing.JButton();
        btnCreatePatientVisits = new javax.swing.JButton();
        btnCreateDiagnosis = new javax.swing.JButton();
        btnCreateLabResult = new javax.swing.JButton();
        btnCreateMedicalHistory = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnReturnToMain = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        DefaultView = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblRegisteredPatients = new javax.swing.JLabel();
        lblRegisteredDoctors = new javax.swing.JLabel();
        lblRegisteredLabProcedures = new javax.swing.JLabel();
        lblRegisteredDiseases = new javax.swing.JLabel();
        lblRegisteredPatientsCount = new javax.swing.JLabel();
        lblRegisteredDoctorsCount = new javax.swing.JLabel();
        lblRegisteredDiseasesCount = new javax.swing.JLabel();
        lblRegisteredLabProceduresCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 153));
        setForeground(java.awt.Color.magenta);

        panelTop.setBackground(new java.awt.Color(51, 102, 255));
        panelTop.setForeground(new java.awt.Color(255, 255, 255));

        lblHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblHeader.setText("Medical Database System");

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblHeader)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelSide.setBackground(new java.awt.Color(227, 227, 227));

        btnPatientRecords.setText("Patient Records");
        btnPatientRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientRecordsActionPerformed(evt);
            }
        });

        btnDoctorRecords.setText("Doctor Records");
        btnDoctorRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorRecordsActionPerformed(evt);
            }
        });

        btnDiseaseRecords.setText("Disease Records");
        btnDiseaseRecords.setToolTipText("");
        btnDiseaseRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiseaseRecordsActionPerformed(evt);
            }
        });

        btnLabProcedures.setText("Lab Procedures");
        btnLabProcedures.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLabProceduresActionPerformed(evt);
            }
        });

        btnCreatePatientVisits.setText("Create Px Visit");
        btnCreatePatientVisits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientVisitsActionPerformed(evt);
            }
        });

        btnCreateDiagnosis.setText("Create Diagnosis");
        btnCreateDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDiagnosisActionPerformed(evt);
            }
        });

        btnCreateLabResult.setText("Create Lab Result");
        btnCreateLabResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateLabResultActionPerformed(evt);
            }
        });

        btnCreateMedicalHistory.setText("Create MedHistory");
        btnCreateMedicalHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateMedicalHistoryActionPerformed(evt);
            }
        });

        btnReports.setBackground(new java.awt.Color(153, 0, 0));
        btnReports.setForeground(new java.awt.Color(255, 255, 255));
        btnReports.setText("REPORTS");
        btnReports.setOpaque(true);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnReturnToMain.setBackground(new java.awt.Color(204, 255, 204));
        btnReturnToMain.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnReturnToMain.setText("RETURN TO MAIN");
        btnReturnToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnToMainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSideLayout = new javax.swing.GroupLayout(panelSide);
        panelSide.setLayout(panelSideLayout);
        panelSideLayout.setHorizontalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSideLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReturnToMain, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateMedicalHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateLabResult, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreatePatientVisits, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLabProcedures, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDiseaseRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctorRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPatientRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        panelSideLayout.setVerticalGroup(
            panelSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPatientRecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoctorRecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDiseaseRecords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLabProcedures)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreatePatientVisits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateDiagnosis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateLabResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreateMedicalHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReturnToMain)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitle.setText("De La Salle Medical Institute");

        lblRegisteredPatients.setText("Current Registered Patients:");

        lblRegisteredDoctors.setText("Current Registered Doctors:");

        lblRegisteredLabProcedures.setText("Current Registered Lab Procedures:");

        lblRegisteredDiseases.setText("Current Registered Diseases:");

        lblRegisteredPatientsCount.setText("0");

        lblRegisteredDoctorsCount.setText("0");

        lblRegisteredDiseasesCount.setText("0");

        lblRegisteredLabProceduresCount.setText("0");

        javax.swing.GroupLayout DefaultViewLayout = new javax.swing.GroupLayout(DefaultView);
        DefaultView.setLayout(DefaultViewLayout);
        DefaultViewLayout.setHorizontalGroup(
            DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefaultViewLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DefaultViewLayout.createSequentialGroup()
                        .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegisteredLabProcedures, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegisteredDiseases, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegisteredDoctors, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegisteredPatients, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(83, 83, 83)
                        .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegisteredDiseasesCount, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblRegisteredPatientsCount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblRegisteredDoctorsCount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lblRegisteredLabProceduresCount, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DefaultViewLayout.setVerticalGroup(
            DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DefaultViewLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisteredPatients)
                    .addComponent(lblRegisteredPatientsCount))
                .addGap(20, 20, 20)
                .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegisteredDoctorsCount, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegisteredDoctors))
                .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DefaultViewLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegisteredLabProcedures)
                            .addComponent(lblRegisteredLabProceduresCount)))
                    .addGroup(DefaultViewLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(DefaultViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRegisteredDiseases, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegisteredDiseasesCount))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.add(DefaultView, "card11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelSide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientRecordsActionPerformed
        MainPanel.removeAll();
        MainPanel.add(patientRecordsView);
        MainPanel.revalidate();
        MainPanel.repaint();

        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnPatientRecordsActionPerformed

    private void btnDoctorRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorRecordsActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not implemented");
    }//GEN-LAST:event_btnDoctorRecordsActionPerformed

    private void btnLabProceduresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLabProceduresActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not implemented");
    }//GEN-LAST:event_btnLabProceduresActionPerformed

    private void btnDiseaseRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiseaseRecordsActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not implemented");
    }//GEN-LAST:event_btnDiseaseRecordsActionPerformed

    private void btnCreateMedicalHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateMedicalHistoryActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not implemented");
    }//GEN-LAST:event_btnCreateMedicalHistoryActionPerformed

    private void btnCreateLabResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateLabResultActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not implemented");
    }//GEN-LAST:event_btnCreateLabResultActionPerformed

    private void btnCreateDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDiagnosisActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Not implemented");
    }//GEN-LAST:event_btnCreateDiagnosisActionPerformed

    private void btnCreatePatientVisitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientVisitsActionPerformed
        MainPanel.removeAll();
        MainPanel.add(patientVisitView);
        MainPanel.revalidate();
        MainPanel.repaint();

        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCreatePatientVisitsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        MainPanel.removeAll();
        MainPanel.add(recordsView);
        MainPanel.revalidate();
        MainPanel.repaint();

        this.pack();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnReturnToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnToMainActionPerformed
        MainPanel.removeAll();
        MainPanel.add(DefaultView);
        MainPanel.revalidate();
        MainPanel.repaint();

        this.pack(); // Optional: resize the frame to match the default panel
        this.setLocationRelativeTo(null); // Optional: re-center the window
    }//GEN-LAST:event_btnReturnToMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainView(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DefaultView;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnCreateDiagnosis;
    private javax.swing.JButton btnCreateLabResult;
    private javax.swing.JButton btnCreateMedicalHistory;
    private javax.swing.JButton btnCreatePatientVisits;
    private javax.swing.JButton btnDiseaseRecords;
    private javax.swing.JButton btnDoctorRecords;
    private javax.swing.JButton btnLabProcedures;
    private javax.swing.JButton btnPatientRecords;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnReturnToMain;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblRegisteredDiseases;
    private javax.swing.JLabel lblRegisteredDiseasesCount;
    private javax.swing.JLabel lblRegisteredDoctors;
    private javax.swing.JLabel lblRegisteredDoctorsCount;
    private javax.swing.JLabel lblRegisteredLabProcedures;
    private javax.swing.JLabel lblRegisteredLabProceduresCount;
    private javax.swing.JLabel lblRegisteredPatients;
    private javax.swing.JLabel lblRegisteredPatientsCount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel panelSide;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
