/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import controller.PatientVisitService;
import dto.ServiceResult;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;

/**
 *
 * @author ACER
 */
public class PatientVisitView extends javax.swing.JPanel {
    private final Connection connection;

    /**
     * Creates new form PatientVisitView
     */
    public PatientVisitView() {
        this(null);
    }

    public PatientVisitView(Connection connection) {
        this.connection = connection;
        initComponents();
        this.setPreferredSize(new Dimension(500, 600));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDob = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblLastName1 = new javax.swing.JLabel();
        txtDob1 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtDob2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        txtDob.setText("yyyy-MM-dd");
        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });

        lblLastName.setText("Patient ID:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        lblLastName1.setText("Doctor ID:");

        txtDob1.setText("yyyy-MM-dd");
        txtDob1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDob1ActionPerformed(evt);
            }
        });

        jTextField1.setText("reason");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Reason:");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtDob2.setText("visit_id");
        txtDob2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDob2ActionPerformed(evt);
            }
        });

        jButton3.setText("Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter visit ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jButton1)
                        .addComponent(lblLastName)
                        .addComponent(lblLastName1)
                        .addComponent(txtDob1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                        .addComponent(txtDob)
                        .addComponent(jTextField1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(jButton3))
                        .addComponent(txtDob2))
                    .addComponent(jLabel2))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLastName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblLastName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDob1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDob2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtDob1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDob1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDob1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PatientVisitService service = new PatientVisitService(connection);
        try {
            int patientId = Integer.parseInt(txtDob.getText().trim());
            int doctorId = Integer.parseInt(txtDob1.getText().trim());
            String reason = jTextField1.getText().trim();

            model.PatientVisit visit = new model.PatientVisit();
            visit.setPatientId(patientId);
            visit.setDoctorId(doctorId);
            visit.setReason(reason);
            visit.setDateTime(new java.sql.Timestamp(System.currentTimeMillis()));

            ServiceResult result = service.addVisit(visit);
            javax.swing.JOptionPane.showMessageDialog(this, result.getMessage());

            if (result.getStatus()) {
                loadVisitsToTable();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid input for IDs.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        PatientVisitService service = new PatientVisitService(connection);
        try {
            int visitId = Integer.parseInt(txtDob2.getText().trim());
            ServiceResult result = service.deleteVisit(visitId);
            javax.swing.JOptionPane.showMessageDialog(this, result.getMessage());

            if (result.getStatus()) {
                loadVisitsToTable();
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric Visit ID.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtDob2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDob2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDob2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        PatientVisitService service = new PatientVisitService(connection);
        try {
            int visitId = Integer.parseInt(txtDob2.getText().trim());
            model.PatientVisit v = service.getVisitById(visitId);
            javax.swing.table.DefaultTableModel modelTbl = new javax.swing.table.DefaultTableModel(
                    new String[]{"Visit ID", "Patient ID", "Doctor ID", "Reason", "Date"}, 0);
            if (v != null) {
                Object[] row = {v.getVisitId(), v.getPatientId(), v.getDoctorId(), v.getReason(), v.getDateTime()};
                modelTbl.addRow(row);
            }
            jTable1.setModel(modelTbl);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter a valid numeric Visit ID.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void loadVisitsToTable() {
        PatientVisitService service = new PatientVisitService(connection);
        List<model.PatientVisit> visits = service.getAllVisits();

        DefaultTableModel modelTbl = new DefaultTableModel(
                new String[]{"Visit ID", "Patient ID", "Doctor ID", "Reason", "Date"}, 0);

        if (visits != null) {
            for (model.PatientVisit v : visits) {
                Object[] row = {v.getVisitId(), v.getPatientId(), v.getDoctorId(), v.getReason(), v.getDateTime()};
                modelTbl.addRow(row);
            }
        }

        jTable1.setModel(modelTbl);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtDob1;
    private javax.swing.JTextField txtDob2;
    // End of variables declaration//GEN-END:variables
}
