/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author ACER
 */
public class RecordsView extends javax.swing.JPanel {

    /**
     * Creates new form RecordsView
     */
    public RecordsView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngChoices = new javax.swing.ButtonGroup();
        lblSelectType = new javax.swing.JLabel();
        cbReportType = new javax.swing.JComboBox<>();
        btngHours = new javax.swing.JRadioButton();
        btngDays = new javax.swing.JRadioButton();
        btngYear = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lblSelectType.setText("Select the type of Report: ");

        cbReportType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disease Trends", "Doctor Activity", "Lab Procedure", "Patient Visits" }));
        cbReportType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbReportTypeActionPerformed(evt);
            }
        });

        btngChoices.add(btngHours);
        btngHours.setText("Past 24 Hours");
        btngHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngHoursActionPerformed(evt);
            }
        });

        btngChoices.add(btngDays);
        btngDays.setText("Past 30 Days");
        btngDays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngDaysActionPerformed(evt);
            }
        });

        btngChoices.add(btngYear);
        btngYear.setText("Past year");
        btngYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngYearActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectType, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(cbReportType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btngYear)
                            .addComponent(btngDays)
                            .addComponent(btngHours))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblSelectType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbReportType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btngHours)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btngDays)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btngYear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbReportTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbReportTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbReportTypeActionPerformed

    private void btngHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngHoursActionPerformed

    private void btngDaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngDaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngDaysActionPerformed

    private void btngYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngYearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btngChoices;
    private javax.swing.JRadioButton btngDays;
    private javax.swing.JRadioButton btngHours;
    private javax.swing.JRadioButton btngYear;
    private javax.swing.JComboBox<String> cbReportType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSelectType;
    // End of variables declaration//GEN-END:variables
}
